services:
  - type: web
    name: noble-travel-agency-portal
    env: node
    buildCommand: npm install && node ./node_modules/vite/bin/vite.js build && node ./node_modules/esbuild/bin/esbuild server.ts --bundle --platform=node --format=cjs --packages=external --sourcemap --outfile=dist/server.cjs
    startCommand: npm start
    disk:
      name: noble-data
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
